### ISSUE TITLE
Update milestones

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#1]
### Tasks
- [ ] Update [Milestones](https://github.com/calab-ntu/libyt/wiki/Milestones)
  - [x] Contents
  - [x] Overview
    - [x] Basic Idea
    - [x] Support Python Versions
    - [x] `yt` Supported Operations
    - [x] Procedure and `libyt` API
    - [x] Inline Python Script
    - [x] Example
  - [x] Embedded Python in C/C++ Application
    - [x] Create `libyt python module`
    - [x] Initialize Embedded Python and Load User Script
    - [x] Load Data Through Python API
    - [x] Load Data Through NumPy API
    - [x] Free Resource in Python and Finalize Embedded Python
    - [x] Connect `libyt` to `yt` by `libyt frontend`
  - [x] Parallelization
    - [x] Install `mpi4py`
    - [x] Enable Parallelism and Inline-Analysis in `yt`
    - [x] Parallel Process in `yt`
    - [x] Record MPI Rank in `libytGrid`
  - [x] Support In-Memory Fields and Collect Hierarchy
    - [x] Load Hierarchy Information and Field Data at Local Rank
    - [x] Collect Hierarchy in Each Rank
    - [x] Connect In-Memory Field Data and Information to Python
  - [x] Support Derived Fields
    - [x] Set Field Information for Derived Fields
    - [x] Connect Derived Field Data to Python
  - [x] Support Particles
    - [x] Set Particle Information
    - [x] Connect Particle Data to Python
  - [ ] Code Structure
    - [x] Configuration
      - [x] Check Data or Not
    - [ ] `libyt` API (_future, if have time. I think the comments in the source code is clear enough._)
    - [x] `libyt` Data Type
    - [x] `libyt python module`
- [x] Examine all links
- [ ] Review each section.
- [x] Book mode
- [x] GitHub wiki

### Links
https://hackmd.io/@Viukb0eMS-aeoZQudVyJ2w/ryCYwu0xF

**Comment by cindytsai** [comment]
Can I write it with `.md` files instead on wiki page, so that I can PR.

**Comment by cindytsai** [comment]
That's it for now...
