### ISSUE TITLE
Polishment

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#11]
### Tasks
- [x] Validate hierarchy: similar to `_validate_parent_children_relasionship` in `yt/frontends/gamer/data_structures.py` but make it more general
  - Probably embed it in `yt_check_grid`
  - The grid id should be in range `0` ~ `num_grids - 1`
  - Root level starts at `0`.
  - If there is no parent grid, parent grid id should set to `-1`.
- [x] Communicate between libyt frontend and simulation frontends
  - Already support loading fields from a simulation frontend
  - Used option: Load all key-value pair in `libyt.param_user` dictionary to `class libytDataset`.
- [ ] Support `dimensionality < 3`
  - #45 
- [x] MPI can’t transfer array length bigger than `int` , so `libyt` abort when `long num_grids` exceed size of `int`
- [x] Update the check at edge when periodic condition. `periodic[3]` and `grid_left_edge[3]` and `grid_right_edge[3]` ( #5 )
- [ ] yt inline python script
  - [ ] file name is fixed, should we make it changeable in every round?
  - #45 
- [x] Rename confusing function names in `yt_get_gridsPtr` and `yt_add_grids` . Change `yt_add_grids` to `yt_commit_grids`
- [x] Determine API procedure
  - Option 1 (now): `yt_get_gridsPtr` -> `yt_commit_grids()` -> `yt_inline` -> `yt_free_grids()`
  - Option 2: Call `yt_add_grid()` `num_grids_local` times ->`yt_inline`
- [x] Input called python function name in every round of inline-analyze
- [x] User should input different fig_basename, otherwise they will be over-written. Solution: Append number of calls to inline script at the end of the fig_basename.
- [x] Do inline-analysis other than `yt_inline_ProjectionPlot()`. Make it can perform input parameter to function like `yt_inline_ProjectionPlot(a,b,c)` ...etc.
- [ ] Support `yt_add_user_parameter_*` can add type other than scalar or a 3-dim vector.
  - #45 
- [x] Check the python reference counting

### Polishment and Optimization
- [ ] Set MPI root rank, for now, it's fixed to rank0.
  - #45 
- [x] Error message format
- [ ] Names for input parameter, some might be a little bit confusing
  - Change `data_dim` to `data_dimensions`.
- [x] Name of the `libyt` API
