### ISSUE TITLE
Demonstrate derived field with EoS

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#19]
### Tasks
- [x] Add a temperature derived field in `GAMER` for `libyt` by calling [Hydro_Con2Temp()](https://github.com/gamer-project/gamer/blob/master/src/Model_Hydro/CPU_Hydro/CPU_Shared_FluUtility.cpp#L674) 
- [x] Compute gas temperature in the `ClusterMerger` test problem and compare with the post-processing script `gamer/example/test_problem/Hydro/ClusterMerger/yt_script/plot_slice-z.py`
- [x] If possible, compute temperature/pressure/entropy in the CCSN simulations. (We tested entropy instead)

**Check on `libyt` derived function functionality**
- [x] Compare temperature calculate through EoS `libyt` derived function and post-processing temperature output directly by `gamer`.

### Related tasks
- #18

**Comment by cindytsai** [comment]
@hyschive Do we still need this?

**Comment by hyschive** [comment]
@cindytsai I think we can close it since computing entropy in the CCSN simulation already demonstrates it. Do you agree?

**Comment by cindytsai** [comment]
@hyschive yes!
