### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#2]
### Tasks
- [x] Small module: call C function in python script to collect particle data
  - [x] libyt should provide a function pointer to this function
  - [x] Simulation codes should fill in this function
- [x] Additional check how yt operates particle objects
  - Parents might not have their children’s particle data, need to get them from other MPI ranks.
  - When not in highest AMR level, how yt get particles in that level?
    - Try covering_grid for example.
- [x] Support multiple particle types
  - [x] `libyt`
    - [x] Read: GAMER particle in HDF5
    - [x] Bridge _read_particle_fields in io.py with simulation code using libyt 
      - [x] Add read particle function when initializing libyt python module 
      - [x] Determine what should user input to libyt
      - [x] Update yt_type_grid.h, so that it stores particle count of different ptype.
      - [x] Update `example` in `libyt`.  
      - [x] Check procedure 
  - [x] yt
    - [x] Read: _read_particle_fields in io.py
    - [x] Connect libyt frontend with this function
- [x] Test with GAMER 
- [x] Test particle filter (e.g., see this [example](https://github.com/gamer-project/gamer/blob/master/example/test_problem/Hydro/AGORA_IsolatedGalaxy/yt_script/plot_star_formation_rate.py#L19))
