### ISSUE TITLE
Test GAMER

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#5]
### Tasks
- [ ] Test libyt with GAMER
  - [x] Various yt functionalites
    - [x] [Check table](https://hackmd.io/ONMFLyfIQrm5VMkG2VNAaw#yt-Supported-Operations)
    - [x] When selecting data. (For example, sphere objects)
  - [x] Derived fields
  - [x] MHD
  - [x] Particles
  - [x] Check Data Test on Periodic Condition. (Remember to turn on `check_data` at `yt_param_libyt`)
    - [x] The [check list](https://hackmd.io/LAMTxFrTQO-f_dQT2AXT7g#Check-List) does not consider period condition. Test if it works.
  - [x] MPI parallelization
  - [ ] OpenMP parallelization
    - `gamer` itself supports OpenMP, but not `libyt`. 
  - [x] Performance
  - [x] Memory consumption and deallocation
  
* Related test on 
  * #14 
  * #19 
  * #43

**Comment by cindytsai** [comment]
Would test OpenMP after `libyt` supports OpenMP.
