### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/libyt#9]
###Tasks
- [ ] Release the code (#8)
- [ ] Work with Matt
- [ ] Where to submit (e.g., ApJS)?

**Comment by cindytsai** [comment]
## Example Papers
- [yt](https://iopscience.iop.org/article/10.1088/0067-0049/192/1/9)
- [Trident](https://iopscience.iop.org/article/10.3847/1538-4357/aa7e2d)
- [Galaxy Cluster Merger Catalog](https://iopscience.iop.org/article/10.3847/1538-4365/aa99db/pdf)

**Comment by cindytsai** [comment]
## ApJS-yt

### ABSTRACT
- Why they developed `yt`.
- Functionality and usage of `yt`.
- How `yt` is structured and its underlying numerical methods and algorithms.
- Key words.

### INTRODUCTION
- Why developed `yt` and its position in analytical tools.
- Timeline and revolution of `yt`.
- Brief introduction and advantages of `yt`.
  - Programming language.
  - Where will you use `yt`.
  - What platform does `yt` runs on.
  - Used example and production run.
- Structure of this paper.

**Comment by cindytsai** [comment]
## Outline of the Paper

### ABSTRACT

### 1. INTRODUCTION
- Why develop libyt?
- Advantage and usage of libyt?
- Introducing libyt:
  - libyt originated in Enzo.
  - Basic idea of libyt.
  - libyt is built with C++ and Python. It is aimed for all C++ simulation codes that are supported by yt.
  - Show libyt has already and can be implemented in simulation codes.
    - Gamer
    - Enzo
  - Example.
    - A time series of very big data sets.
 - Supoprted yt functionalities.
   - Basically all...
- Outline of this paper.

### 2. MECHANISMS FOR DOING INLINE-ANALYSIS IN PARALLEL

#### 2.1 Embedding Python in C++ Application
- Brief description of Python and NumPy API.
- Creation of libyt Python module.
- How it loads data from C++ to Python.
- Building C++ extended Python methods.
- Loading user's inline Python script.

#### 2.2 Connecting libyt to yt
- View libyt as another yt frontend.
- How libyt inherit other frontend's field definitions.

#### 2.3 Parallelism
- How libyt is paralleled is heavily rely on yt.
  - Some distribute jobs according to where the grids data are stored. (ex: Projection)
  - Others. (ex: Slice)
- How to deal with getting non-local data.

### 3. CODE METHOD
#### 3.1 Supporting In-Memory Field Data and Collecting Grid Information
- Collecting hierarchy from each rank.
- Connect in-memory field data to Python.
  - Supporting ghost zone.

#### 3.2 Supporting Derived Fields
- Definition of derived fields.
- Why do we need this?
  - Some calculations cannot be done in yt. (ex: EoS, #19 )
  - Save memory space. (ex: MHD face-centered to cell-centered.)
- How required data is generated and passed back to Python.

#### 3.3 Supporting Particle Data
- Particle data type may be discrete and is not a contiguous array in memory space.
- How to collect discrete data and pass back to Python.

### 4. DEMONSTRATION: HOW TO IMPLEMENT LIBYT TO SIMULATION CODE
- libyt is aimed for all frontends supported by yt.
- A C++ library for yt.

#### 4.1 Initialization
#### 4.2 Setting yt Parameters
#### 4.3 Setting Code Specific Parameters
#### 4.4 Setting Fields Information
#### 4.5 Setting Particles Information
#### 4.6 Setting Local Grids Information
#### 4.7 Commiting Your Settings
#### 4.8 Performing Inline-Analysis
- How to use `yt_inline` and `yt_inline_argument`
- How to convert your post-processing script to inline script.
#### 4.9 Freeing Resource
#### 4.10 Finalization

### 5. PRODUCTION RUN AND PERFORMANCES
- #19 
- Time Consumption - Number of Nodes graph.

### 6. FUTURE DIRECTIONS
- Support Fortran (ex: FLASH).
- Support ParaView for inline-rendering. libyt has the potential to give another way for simulation codes to support inline-analysis in ParaView.
